server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blackout_monitor
    username: postgres
    password: postgres

telegram:
  bot:
    enable:
    token:
    name:
    webhook-path:
